# Este workflow traera el contenido del repositorio base a este para posteriormente analizarlo y llevar a cabo la ejecucion
name: update_media

on:
    # Una vez cada hora ( que coincide con la periodica actualizacion del repositorio base )
    # Se actualizara, trayendo todos los paquetes y sustituyendolos por los que ya se tienen
    schedule:
        - cron: '5 * * * *'  # Se ejecuta cada hora, 5 minutos después de la hora

# El resto del cotenido se tendra que ver segun como queremo que se alamacene el mismo
# Es necesario sentar lasbases para crear un arbol de directorios y la base de datos